[package]
name = "pallet-did"
version = '2.0.0-alpha.6'
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
    'timestamp/std',
]

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.6'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.timestamp]
default_features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.6'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.6'
